"""Golden markdown fixtures — the backend half of the parity suite.

`fixtures/markdown/` holds language-agnostic pairs: `<name>.md` (canonical
markdown) and `<name>.doc.json` (the ProseMirror doc, generated by
`tools/markdown_fixtures.py`). This file pins the *Python* serializer and
parser to the pairs; `frontend/src/lib/__tests__/markdownGolden.test.ts`
pins the *TypeScript* serializer to the same files — so the copy button,
the /document endpoint, and `datasette paper export` all produce identical
bytes for the covered constructs.

If a change here fails: either fix the divergence, or (for a deliberate
format change) update the .md, rerun the generator, and confirm the
frontend runner still passes.
"""

# @feat cli-export: golden parity — Python serializer/parser pinned to shared fixtures

import json
from pathlib import Path

import pytest

from datasette_paper.markdown import doc_to_markdown
from datasette_paper.markdown_parser import markdown_to_doc

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "markdown"
NAMES = sorted(p.stem for p in FIXTURES.glob("*.md") if p.stem != "README")


def _pair(name: str) -> tuple[str, dict]:
    md = (FIXTURES / f"{name}.md").read_text()
    doc = json.loads((FIXTURES / f"{name}.doc.json").read_text())
    return md, doc


def test_fixture_pairs_complete():
    assert NAMES, "no fixtures found"
    for name in NAMES:
        assert (FIXTURES / f"{name}.doc.json").exists(), (
            f"{name}.md has no {name}.doc.json — run"
            " `uv run --prerelease=allow python tools/markdown_fixtures.py`"
        )


@pytest.mark.parametrize("name", NAMES)
def test_serializer_matches_golden(name):
    md, doc = _pair(name)
    assert doc_to_markdown(doc) == md


@pytest.mark.parametrize("name", NAMES)
def test_parser_roundtrips_golden(name):
    md, doc = _pair(name)
    assert markdown_to_doc(md) == doc


# Nodes a .md-authored fixture can never contain, with why. The fixtures are
# generated by parsing markdown, so a node the parser never emits can't
# appear — its serializer output must be pinned per-side instead (and is:
# `{{key}}` in test_markdown.py's inline-atom round-trip and
# markdownSerializer.test.ts's inline-atoms test).
UNFIXTURABLE = {
    "doc",  # the serialization root, not content
    "placeholder",  # write-only: substituted at create-from-template, never parsed back
}


def test_fixtures_cover_every_schema_node():
    """Enforce the README's coverage claim: every node in the shared schema
    (minus the documented UNFIXTURABLE set) has at least one ordinary
    representative across the fixtures, so a new node can't silently bypass
    cross-language parity coverage.
    """
    from datasette_paper.pm_schema import schema

    covered: set[str] = set()

    def walk(node: dict) -> None:
        covered.add(node.get("type", ""))
        for child in node.get("content") or []:
            walk(child)

    for name in NAMES:
        _md, doc = _pair(name)
        walk(doc)

    missing = set(schema.nodes.keys()) - covered - UNFIXTURABLE
    assert missing == set(), (
        f"schema nodes with no golden fixture coverage: {sorted(missing)} —"
        " add an ordinary representative to fixtures/markdown/ (or, if the"
        " parser can never emit it, add it to UNFIXTURABLE with a reason and"
        " pin its serialization in both per-side unit suites)"
    )
