"""AUTOGENERATED by tools/gen_queries.py — do not edit.

Regenerate with `just codegen-queries` after editing
datasette_paper/sql/queries.sql.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Any


@dataclass
class Doc:
    id: int
    name: str
    created_at: str
    updated_at: str
    created_by: str | None
    schema_name: str
    current_version: int
    visibility: str
    state: str
    archived_at: str | None
    trashed_at: str | None
    delete_at: str | None
    kind: str
    locked: int


@dataclass
class Step:
    doc_id: int
    version: int
    client_id: int
    actor_id: str | None
    step_json: str
    created_at: str


@dataclass
class Snapshot:
    doc_id: int
    version: int
    doc_json: str
    created_at: str


@dataclass
class Share:
    actor_id: str
    role: str
    granted_by: str | None
    granted_at: str


def insert_doc(
    conn: sqlite3.Connection,
    name: str,
    created_by: str | None,
    schema_name: str,
    kind: str,
) -> Doc | None:
    sql = """\
INSERT INTO _datasette_paper_doc (name, created_by, schema_name, kind)
VALUES ($name::text, $created_by::text::, $schema_name::text, $kind::text)
RETURNING id, name, created_at, updated_at, created_by, schema_name, current_version, visibility, state, archived_at, trashed_at, delete_at, kind, locked;
"""
    params = {
        "name::text": name,
        "created_by::text::": created_by,
        "schema_name::text": schema_name,
        "kind::text": kind,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Doc(*row) if row is not None else None


def update_doc_name(conn: sqlite3.Connection, name: str, doc_id: int) -> Doc | None:
    sql = """\
UPDATE _datasette_paper_doc
SET name = $name::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $doc_id::integer
RETURNING id, name, created_at, updated_at, created_by, schema_name, current_version, visibility, state, archived_at, trashed_at, delete_at, kind, locked;
"""
    params = {"name::text": name, "doc_id::integer": doc_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Doc(*row) if row is not None else None


def select_doc_by_id(conn: sqlite3.Connection, doc_id: int) -> Doc | None:
    sql = """\
SELECT id, name, created_at, updated_at, created_by, schema_name, current_version, visibility, state, archived_at, trashed_at, delete_at, kind, locked
FROM _datasette_paper_doc
WHERE id = $doc_id::integer;
"""
    params = {"doc_id::integer": doc_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Doc(*row) if row is not None else None


def list_docs(conn: sqlite3.Connection) -> list[Doc]:
    sql = """\
SELECT id, name, created_at, updated_at, created_by, schema_name, current_version, visibility, state, archived_at, trashed_at, delete_at, kind, locked
FROM _datasette_paper_doc
ORDER BY created_at;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [Doc(*row) for row in cursor.fetchall()]


def list_docs_by_ids_states_and_kinds(
    conn: sqlite3.Connection, doc_ids_json: str, states_json: str, kinds_json: str
) -> list[Doc]:
    sql = """\
SELECT id, name, created_at, updated_at, created_by, schema_name, current_version, visibility, state, archived_at, trashed_at, delete_at, kind, locked
FROM _datasette_paper_doc
WHERE id IN (
    SELECT CAST(value AS INTEGER) FROM json_each($doc_ids_json::text)
)
  AND state IN (
    SELECT value FROM json_each($states_json::text)
)
  AND kind IN (
    SELECT value FROM json_each($kinds_json::text)
)
ORDER BY updated_at DESC;
"""
    params = {
        "doc_ids_json::text": doc_ids_json,
        "states_json::text": states_json,
        "kinds_json::text": kinds_json,
    }
    cursor = conn.execute(sql, params)
    return [Doc(*row) for row in cursor.fetchall()]


def archive_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET state = 'archived',
    archived_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
    trashed_at = NULL,
    delete_at = NULL
WHERE id = $doc_id::integer;
"""
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def unarchive_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET state = 'active',
    archived_at = NULL,
    trashed_at = NULL,
    delete_at = NULL
WHERE id = $doc_id::integer;
"""
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def trash_doc(conn: sqlite3.Connection, delete_at: str, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET state = 'trashed',
    trashed_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
    delete_at = $delete_at::text
WHERE id = $doc_id::integer;
"""
    params = {"delete_at::text": delete_at, "doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def restore_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET state = 'active',
    archived_at = NULL,
    trashed_at = NULL,
    delete_at = NULL
WHERE id = $doc_id::integer;
"""
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def list_trashed_to_delete(conn: sqlite3.Connection, now: str) -> list[Doc]:
    sql = """\
SELECT id, name, created_at, updated_at, created_by, schema_name, current_version, visibility, state, archived_at, trashed_at, delete_at, kind, locked
FROM _datasette_paper_doc
WHERE state = 'trashed'
  AND delete_at IS NOT NULL
  AND delete_at < $now::text
ORDER BY delete_at;
"""
    params = {"now::text": now}
    cursor = conn.execute(sql, params)
    return [Doc(*row) for row in cursor.fetchall()]


def set_doc_kind(conn: sqlite3.Connection, kind: str, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET kind = $kind::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $doc_id::integer;
"""
    params = {"kind::text": kind, "doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def set_doc_locked(conn: sqlite3.Connection, locked: int, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET locked = $locked::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $doc_id::integer;
"""
    params = {"locked::integer": locked, "doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def delete_steps_for_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = "DELETE FROM _datasette_paper_step WHERE doc_id = $doc_id::integer;"
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def delete_snapshots_for_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = "DELETE FROM _datasette_paper_snapshot WHERE doc_id = $doc_id::integer;"
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def hard_delete_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = "DELETE FROM _datasette_paper_doc WHERE id = $doc_id::integer;"
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def insert_step(
    conn: sqlite3.Connection,
    doc_id: int,
    client_id: int,
    actor_id: str | None,
    step_json: str,
) -> int | None:
    sql = """\
INSERT INTO _datasette_paper_step (doc_id, version, client_id, actor_id, step_json)
VALUES (
    $doc_id::integer,
    (SELECT current_version + 1 FROM _datasette_paper_doc WHERE id = $doc_id::integer),
    $client_id::integer,
    $actor_id::text::,
    $step_json::text
)
RETURNING version;
"""
    params = {
        "doc_id::integer": doc_id,
        "client_id::integer": client_id,
        "actor_id::text::": actor_id,
        "step_json::text": step_json,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def bump_doc_version(conn: sqlite3.Connection, version: int, doc_id: int) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET current_version = $version::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $doc_id::integer;
"""
    params = {"version::integer": version, "doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def select_steps_after(
    conn: sqlite3.Connection, doc_id: int, after_version: int
) -> list[Step]:
    sql = """\
SELECT doc_id, version, client_id, actor_id, step_json, created_at
FROM _datasette_paper_step
WHERE doc_id = $doc_id::integer
  AND version > $after_version::integer
ORDER BY version;
"""
    params = {"doc_id::integer": doc_id, "after_version::integer": after_version}
    cursor = conn.execute(sql, params)
    return [Step(*row) for row in cursor.fetchall()]


def select_max_version(conn: sqlite3.Connection, doc_id: int) -> Any | None:
    sql = "SELECT MAX(version) FROM _datasette_paper_step WHERE doc_id = $doc_id::integer;"
    params = {"doc_id::integer": doc_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def insert_snapshot(
    conn: sqlite3.Connection,
    doc_id: int,
    version: int,
    doc_json: str,
    actor_id: str | None,
) -> None:
    sql = """\
INSERT INTO _datasette_paper_snapshot (doc_id, version, doc_json, actor_id)
VALUES ($doc_id::integer, $version::integer, $doc_json::text, $actor_id::text::);
"""
    params = {
        "doc_id::integer": doc_id,
        "version::integer": version,
        "doc_json::text": doc_json,
        "actor_id::text::": actor_id,
    }
    conn.execute(sql, params)
    return None


def select_latest_snapshot(conn: sqlite3.Connection, doc_id: int) -> Snapshot | None:
    sql = """\
SELECT doc_id, version, doc_json, created_at
FROM _datasette_paper_snapshot
WHERE doc_id = $doc_id::integer
ORDER BY version DESC
LIMIT 1;
"""
    params = {"doc_id::integer": doc_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Snapshot(*row) if row is not None else None


def select_shares(conn: sqlite3.Connection, doc_id: int) -> list[Share]:
    sql = """\
SELECT actor_id, role, granted_by, granted_at
FROM _datasette_paper_share
WHERE doc_id = $doc_id::integer
ORDER BY actor_id;
"""
    params = {"doc_id::integer": doc_id}
    cursor = conn.execute(sql, params)
    return [Share(*row) for row in cursor.fetchall()]


def update_doc_visibility(
    conn: sqlite3.Connection, visibility: str, doc_id: int
) -> None:
    sql = """\
UPDATE _datasette_paper_doc
SET visibility = $visibility::text
WHERE id = $doc_id::integer;
"""
    params = {"visibility::text": visibility, "doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def delete_shares_for_doc(conn: sqlite3.Connection, doc_id: int) -> None:
    sql = "DELETE FROM _datasette_paper_share WHERE doc_id = $doc_id::integer;"
    params = {"doc_id::integer": doc_id}
    conn.execute(sql, params)
    return None


def insert_share(
    conn: sqlite3.Connection,
    doc_id: int,
    actor_id: str,
    role: str,
    granted_by: str | None,
) -> None:
    sql = """\
INSERT INTO _datasette_paper_share (doc_id, actor_id, role, granted_by)
VALUES ($doc_id::integer, $actor_id::text, $role::text, $granted_by::text::);
"""
    params = {
        "doc_id::integer": doc_id,
        "actor_id::text": actor_id,
        "role::text": role,
        "granted_by::text::": granted_by,
    }
    conn.execute(sql, params)
    return None
