"""Render docs/TELEMETRY.md from the telemetry registry.
@feat telemetry: the generated reference — `just telemetry-docs` writes it,
`just check-telemetry-docs-fresh` (and test_generated_docs_are_fresh) gate
drift in CI.

Ported in structure from Datasette's docs/telemetry_doc.py — the one piece
the plugin kit does not export — but emitting Markdown and writing the
whole file rather than driving cog: this repo has no cog pipeline, and one
generated file is simpler than adding one.

Usage: uv run --prerelease=allow python tools/telemetry_doc.py [OUT_PATH]
(default: docs/TELEMETRY.md next to the repo root).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from datasette_paper import telemetry_registry as reg  # noqa: E402

PREAMBLE = """\
<!-- generated by `just telemetry-docs`, do not edit -->

# Telemetry

datasette-paper instruments its own hot paths — the collab write
pipeline, SSE streams, instance materialization and the write tail —
with OpenTelemetry, through `opentelemetry-api` only. The plugin never
installs a provider or an exporter: with no SDK in the process every
span is a no-op `NonRecordingSpan`, every instrument does nothing, and
the observable-gauge callbacks never run. Turning telemetry **on** is
the operator's move, exactly as with Datasette core. The easiest way is
the `datasette-otel-otlp` plugin — one config flag, no `OTEL_*`
environment variables, no `opentelemetry-instrument` wrapper:

```bash
datasette --internal internal.db \\
    -s plugins.datasette-otel-otlp.endpoint http://localhost:4318 \\
    -s plugins.datasette-otel-otlp.service_name datasette-paper ...
```

For local development, `just jaeger` (a `jaeger` binary from
https://www.jaegertracing.io/download/ — the UI is at
http://localhost:16686, the :4318 ingest port has no UI) plus
`just dev-otel` gives a browsable trace UI for real editing sessions.

**Metrics:** that plugin exports *traces only* (it installs a
`TracerProvider`, not a `MeterProvider`), and Jaeger ingests traces
only — so under `just dev-otel` the `paper.*` metrics below stay no-op.
To collect them, run under a metrics-capable setup instead, e.g.
`opentelemetry-instrument` (`--with opentelemetry-distro --with
opentelemetry-sdk`) with `OTEL_METRICS_EXPORTER` pointed at an OTLP
metrics backend such as Prometheus or Grafana. The registry below is the
contract either way. See Datasette's own telemetry documentation for the
full operator story.

Every signal below lives in the `datasette_paper` instrumentation scope
under the `paper.*` prefix. All of it is declared in
`datasette_paper/telemetry_registry.py`, and a conformance test holds
the code to this document in both directions.

**Privacy.** No signal carries a person, a document's content, or a
client-chosen string: no actor ids, no doc names, no markdown or step
text, no SQL. Variability is closed enums; sizes are byte counts;
`paper.doc_id` (a server-assigned integer) appears on spans only, never
as a metric dimension. A sentinel-secret test enforces this.

**The SSE route has no spans.** Datasette's request span ends when the
response body finishes, so on a streaming route it stays open for the
whole connection — a documented core caveat ("Streaming responses hold
the request span open", in Datasette's *Telemetry for plugin authors*
page, Known caveats). Paper follows that page's recommended shape:
concurrent-stream gauges, close-reason counters/histograms, and
enrichment of the request span itself (`paper.doc_id`,
`paper.close_reason`, and a `paper.sse.backlog` span event carrying the
flushed step count).

**Nesting.** `paper.*` spans nest under Datasette's request span (and
paper's DB work under core's `db.query` spans) only on a Datasette
recent enough to emit them; on an older Datasette they are their own
roots and everything still works.
"""


def _md(text: str) -> str:
    "Registry descriptions use RST double-backtick literals; fold to Markdown."
    return " ".join(text.replace("``", "`").split())


def _attribute_line(attribute) -> str:
    parts = [f"- `{attribute}`"]
    if attribute.optional:
        parts.append("*(optional)*")
    parts.append("—")
    parts.append(_md(attribute.description))
    if attribute.values is not None:
        values = ", ".join(f"`{value}`" for value in sorted(attribute.values))
        parts.append(f"One of: {values}.")
    return " ".join(parts)


def render() -> str:
    lines = [PREAMBLE]

    lines.append("\n## Spans\n")
    lines.append(
        "All spans are `SpanKind.INTERNAL` with fixed names; variability "
        "goes in attributes. There is deliberately no `paper.db.query` "
        "span — every `PaperDB` call already gets core's `db.query` span "
        "(kind `CLIENT`, attribute `datasette.callback` naming the query "
        "helper); paper adds the per-helper `paper.db.query.duration` "
        "histogram instead.\n"
    )
    for span in reg.SPANS:
        lines.append(f"### `{span}`\n")
        lines.append(_md(span.description) + "\n")
        if span.attributes:
            for attribute in span.attributes:
                lines.append(_attribute_line(attribute))
            lines.append("")

    lines.append("## Metrics\n")
    lines.append(
        "Duration histograms are in seconds on Datasette's shared "
        "`DURATION_BUCKETS` boundaries, so a paper p95 reads against a "
        "core p95 on the same axis. Counters and gauges carry only the "
        "attributes listed.\n"
    )
    for metric in reg.METRICS:
        lines.append(f"### `{metric}`\n")
        lines.append(f"*{metric.kind}, unit `{metric.unit}`.*\n")
        lines.append(_md(metric.description) + "\n")
        if metric.attributes:
            for attribute in metric.attributes:
                lines.append(_attribute_line(attribute))
            lines.append("")
        if metric.buckets is not None:
            buckets = ", ".join(str(boundary) for boundary in metric.buckets)
            lines.append(f"Bucket boundaries: {buckets}.\n")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    default = Path(__file__).resolve().parent.parent / "docs" / "TELEMETRY.md"
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else default
    out.write_text(render())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
